[package]
name = "blockchain-benchmark"
version = "0.1.0"
authors = ["daniel"]
edition = "2018"

[dependencies]
tera = "1"
hyper = "0.13"
tokio = { version = "0.2.13", features = ["full"] }
tower-web = "0.3.7"